"""initial migrate

Revision ID: 768e73ec12a6
Revises: 
Create Date: 2021-03-06 18:09:56.685915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768e73ec12a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_data')
    # ### end Alembic commands ###
